#!/bin/bash

MACHINES=""

#while read i; do
#        mkdir -p /var/log/nfcapd/$i
#        chown nfcapd:nfcapd /var/log/nfcapd/$i
#        MACHINES+="-n $i,$i,/var/log/nfcapd/$i "
#done </etc/nfcapd.conf

#echo "MACHINES="$MACHINES

#FLAGS="-u nfcapd -g nfcapd -t 300 -D -T all -p 2055 -S 0 -B 1024000 "
#FLAGS+=$MACHINES

#echo "FLAGS="$FLAGS

FLAGS="-u nfcapd -g cgred -t 300 -T all -p 2055 -S 0 -B 1024000 -l /var/log/nfcapd"

DAEMON_OPTIONS=$FLAGS
