#!/bin/sh
# 
### BEGIN INIT INFO
# Provides:          nfcapd
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: netflow capture daemon
# Description: 	     netflow capture daemon
# chkconfig: 345 99 01
# processname: nfcapd
# File: nfcapd
### END INIT INFO

#
# Author : Michael Fung (http://3open.org/)
# 

# Source function library.
. /etc/init.d/functions

# Source an auxiliary options file if we have one, and pick up DAEMON_OPTIONS.
[ -r /etc/sysconfig/nfcapd ] && . /etc/sysconfig/nfcapd

DAEMON=nfcapd
LOCK_FILE="/var/lock/subsys/$DAEMON"
RETVAL=0
  
status_nfcapd () {
	if pidof $DAEMON > /dev/null 2>&1; then
		return 0
	else
	  return 1
	fi
}

do_start() {
	status_nfcapd
	if [ $? -eq 0 ]; then
		echo "$DAEMON already started..."
		return 1
	fi
	
	echo -n $"Starting $DAEMON: "
	daemon /usr/bin/nfcapd -D $DAEMON_OPTIONS
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch $LOCK_FILE
	return $RETVAL
}

do_stop() {
    echo -n $"Stopping $DAEMON: "
    killproc $DAEMON
    RETVAL=$?
    [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
    echo
    return $RETVAL
}
                
# See how we were called.
case "$1" in
	start)
    do_start
		;;
	
	stop)
		do_stop
    ;;
    
  status)
		status $DAEMON
    ;;

	restart)
		do_stop
		do_start
		;;

	condrestart|try-restart)
                status_nfcapd
                if [ $? -eq 0 ]; then
                        do_stop
                        do_start
                else
                        echo "daemon not running..."
                fi
                ;;

	*)
		echo "Usage: $0 {start|stop|restart|status|condrestart|try-restart}"
		exit 2
		;;

esac
  
exit $RETVAL
  
# End of this script
